server:
  port: ${CONTAINER_PORT:8090}
  error:
    include-message: always

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: course-service-route
              uri: lb://svc-course-service
              predicates:
                - Path=/api/v1/courses/**
            - id: user-service-route
              uri: lb://svc-user-service
              predicates:
                - Path=/api/v1/users/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        registration:
          gateway-client-registration:
            provider: authorization-server-provider
            client-id: gateway-client
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
        provider:
          authorization-server-provider:
            issuer-uri: http://localhost:9000
