apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-authorization-server
data:
  gateway_server_base_url: http://gateway.magadiflo.local:8090
  authorization_server_issuer_uri: http://auth.magadiflo.local:9000
