apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-course-service
data:
  container_port: '8002'
  db_host: svc-postgres
  db_port: '5432'
  db_name: db_course_service
  db_username: postgres
  db_password: magadiflo
  user_service_host: svc-user-service
  user_service_port: '8001'
