apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-user-service
data:
  container_port: '8001'
  db_host: svc-mysql
  db_port: '3306'
  db_name: db_user_service
  db_username: admin
  db_password: magadiflo
  course_service_host: svc-course-service
  course_service_port: '8002'
