apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-user-service
data:
  container_port: '8001'
  db_host: svc-mysql
  db_port: '3306'
  db_name: db_user_service
  k8s_course_service_name: svc-course-service
  authorization_server_issuer_uri: http://auth.magadiflo.local:9000
  spring_profiles_active: dev
  user-service.yml: |-
    config:
      text: Configuraciones del perfil activo [default] desde [user-service-config-map.yml]
  user-service-dev.yml: |-
    config:
      text: Configuraciones del perfil activo [dev] desde [user-service-config-map.yml]
  user-service-prod.yml: |-
    config:
      text: Configuraciones del perfil activo [prod] desde [user-service-config-map.yml]
