apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d-gateway-server
  template:
    metadata:
      labels:
        app: d-gateway-server
    spec:
      containers:
        - image: magadiflo/gateway-server:latest
          name: c-gateway-server
          ports:
            - containerPort: 8090
          env:
            - name: CONTAINER_PORT
              valueFrom:
                configMapKeyRef:
                  name: cm-gateway-server
                  key: container_port
            - name: AUTHORIZATION_SERVER_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: cm-gateway-server
                  key: authorization_server_issuer_uri
            - name: ANGULAR_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-gateway-server
                  key: angular_base_url
            - name: GATEWAY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sec-gateway-server
                  key: gateway_client_secret
