apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: d-mysql
  name: d-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d-mysql
  strategy: {}
  template:
    metadata:
      labels:
        app: d-mysql
    spec:
      containers:
      - image: mysql:8.0.41-debian
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
status: {}
